### ISSUE TITLE
Get request origin

### ISSUE THREAD

**Issue by rodrigoriome** [fjogeleit/http-request-action#27]
Hi! I'm trying to use CORS to prevent any other origins from being able to request my actions endpoint. How can I know the origin of the request coming from this action? By the way, I'm new to GitHub Actions, so if there's a better way people are using to solve this problem, let me know.

Thanks!

**Comment by fjogeleit** [comment]
Hey, I don't think that CORS helps you with this problem. Because its a backend to backend communication - so you don't have an origin header. You can use authentication like HTTP Basic Authentication or a Token approach, this information can be stored as github secrets and is not visible in your action or action output.

**Comment by rodrigoriome** [comment]
Oh I see... You're right. In my particular case, two actors should send a request to my endpoint, GH Actions and a CMS, so I'll probably work something out with tokens. Thanks for the suggestions, feel free to close this issue :)

**Comment by fjogeleit** [comment]
Okay, glad to help. Let me know if you need any help further. Thanks for using my action ;-)
