### ISSUE TITLE
File Uploads with `\` in the path are broken

### ISSUE THREAD

**Issue by hrueger** [fjogeleit/http-request-action#78]
Hi @fjogeleit,
thanks a lot for this excellent action. I'm using in in quite a few projects.

I just spent about an hour trying to figure out why my file was not uploaded. Turns out that this action does not seem to like Windows-style filepaths (with `\`) like they are generated by `path.join(...)` in JS.
When I replace them with forward slashes, everything works as expected.

For example:
```
files: { "file": "D:/a/myApp/myApp/release/My-App-win32-x64-1.0.0.exe" }
```
works, but
```
files: { "file": "D:\a\myApp\myApp\release\My-App-win32-x64-1.0.0.exe" }
```
does not.

**Comment by fjogeleit** [comment]
hey, thanks for reporting. I will have a look when I find some time.

So the action in general is working when you use the `/`. So it is not blocking you?

**Comment by hrueger** [comment]
Thanks for the quick response.

> So the action in general is working when you use the /. So it is not blocking you?

Yes, exactly 👍

**Comment by fjogeleit** [comment]
Okay, thanks.

**Comment by fjogeleit** [comment]
Hey, sorry for the late response,

If this is still relevant for you, I added a path.normalize to let node convert all file paths depending on the operating system. It would be cool if you could test if this solves your issue.

The change is currently available over the develop branch: `fjogeleit/http-request-action@develop`

**Comment by hrueger** [comment]
Hey, no problem. Thanks for the work, I'll test that next week 👍

**Comment by hrueger** [comment]
Hi, sorry for my very late response. We haven't made a release since, so I couldn't test it :-(
I let you know once we do a new release 👍

**Comment by fjogeleit** [comment]
No worries thanks for the update

**Comment by hrueger** [comment]
Hi @fjogeleit,
we just made a release and I tried the `develop` version. However, it is still not working:
```
Run fjogeleit/http-request-action@develop
  with:
    url: ***/release/_ingest/myApp/desktop
    method: POST
    username: ***
    password: ***
    files: { "file": "packages\release\myApp Setup 1.0.0.exe" }
    timeout: 120000
    data: {}
  env:
    NODE_OPTIONS: --max_old_space_size=8048
Error: {"code":400,"message":"No files were uploaded."}
```
Error Code 400 comes from my server.

After a bit more thinking, I don't think `path.normalize` has changed anything here, because this is running on a Windows machine, so it would probably just break the workaround (which was replacing `\` with `/`).

Do you have any idea what is going wrong here?

**Comment by fjogeleit** [comment]
hm yeah, looks like `normalize` doesn't help as expected. Strange that it converts the path in a way that the `fs` module can't handle it.

Maybe the easiest solution is to go with the forward slash and document it for other users. I don't really have an idea right now. The only think I found was that Windows uses `\\` as separator. So maybe it works with the current stable version (without the normalize) and `\\` instead of `\` as separator.

**Comment by hrueger** [comment]
Can't we just replace all `\` with `/`? I don't believe that to have any side effects since you won't have them in file/folder names anyway.

**Comment by fjogeleit** [comment]
Yeah sure, you can still go with that workaround. I will close the normalize PR and add this behavior to the documentation. Nothing more I can do, right now. If this is fine for you I will close the issue

**Comment by hrueger** [comment]
I meant including that workaround in the action itself

**Comment by hrueger** [comment]
But we can also keep it out of there, if you like.

**Comment by fjogeleit** [comment]
Hm not sure if a simple replace could be problematic in some cases where escaped \ part of a path. Could be an edgecase but possible.

**Comment by hrueger** [comment]
Hm, good point.

**Comment by bgerhards-vermeer** [comment]
Do you want to add this as a feature? When looking at Windows paths, when you put them in a string, the requirement (because of backslash default behavior) is to character escape the path.

Example:
`"path\\to\\folder"`

Are there any other packages that exhibit the requested behavior? I know it makes for an easy copy/paste but once someone adds \\ to their path I believe it can cause undesired behavior with double \\ in the output path.

Good luck!

**Comment by fjogeleit** [comment]
Hey, what kind of feature do you mean? Replacing \ with / ?

**Comment by bgerhards-vermeer** [comment]
Yes

**Comment by fjogeleit** [comment]
I may have a look on it and see if I can provide something

**Comment by fjogeleit** [comment]
I did some test and overall it's not possible provide a working solution for it.

It turns out that backslashes in input values are not automatically escaped in strings, so I am also not in the situation to convert them, because I can not filter/target them with an regex. The user must escape the paths themself or directly replace them with forward slashes.
